version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn main:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker
    expose:
      - 5000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)'

  traefik:
    image: traefik:latest
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '$PWD/docker/traefik.dev.yml:/etc/traefik/traefik.dev.yml'